/*
 * The Four Lokos
 * Created by: Serena Herter, Alana Traylor
 * Created on: 4/24/2021
 * This class creates the graphical user interface for the card game application
 */
package View;

import ViewConnectors.UserDataConnector;
import ViewConnectors.WarGameConnector;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CardGameAppUI extends javax.swing.JFrame {

    WarGameConnector wargame = new WarGameConnector();
    UserDataConnector userdata = new UserDataConnector();
    String Name, Username, Password, Email;

    /**
     * Creates new form CardGameAppUI
     */
    public CardGameAppUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logInPanel = new javax.swing.JPanel();
        LogInPageTitlePanel = new java.awt.Panel();
        LogInPageTitleLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordPasswordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        userProfilePanel = new javax.swing.JPanel();
        UserProfilePageTitlePanel = new java.awt.Panel();
        UserProfilePageTitleLabel = new javax.swing.JLabel();
        DynamicUsernameLabel = new javax.swing.JLabel();
        UpdateProfileButton = new javax.swing.JButton();
        DynamicPlayerSinceLabel = new javax.swing.JLabel();
        playerSinceLabel = new javax.swing.JLabel();
        gamesPlayedLabel = new javax.swing.JLabel();
        DynamicGamesPlayedLabel = new javax.swing.JLabel();
        totalWinsLabel = new javax.swing.JLabel();
        DynamicTotalWinsLabel1 = new javax.swing.JLabel();
        leaderBoardPanel = new javax.swing.JPanel();
        LeaderBoardPageTitlePanel = new java.awt.Panel();
        LeaderBoardPageTitleLabel = new javax.swing.JLabel();
        leaderBoardScrollPane = new javax.swing.JScrollPane();
        LeaderBoardTable = new javax.swing.JTable();
        gamePlayPanel = new javax.swing.JPanel();
        GamePlayPageTitlePanel = new java.awt.Panel();
        GamePlayPageTitleLabel = new javax.swing.JLabel();
        computerDeckjButton = new javax.swing.JButton();
        playerDeckButton = new javax.swing.JButton();
        ComputerCardjLabel = new javax.swing.JLabel();
        Player1CardjLabel = new javax.swing.JLabel();
        DynamicPlayerCardsRemainingLabel = new javax.swing.JLabel();
        DynamicComputerCardsRemainingLabel = new javax.swing.JLabel();
        forfeitButton = new javax.swing.JButton();
        WinnerMessageLabel = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        signUpPanel = new javax.swing.JPanel();
        SignUpPageTitlePanel = new java.awt.Panel();
        SignupPageTitleLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        matchPasswordField = new javax.swing.JPasswordField();
        newPasswordField = new javax.swing.JPasswordField();
        emailLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        newUsernameLabel = new javax.swing.JLabel();
        matchPasswordLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        leaderBoardButton = new javax.swing.JButton();
        userProfileButton = new javax.swing.JButton();
        gameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setName("AppUIFrame"); // NOI18N

        mainPanel.setBackground(new java.awt.Color(0, 102, 51));
        mainPanel.setLayout(new java.awt.CardLayout());

        logInPanel.setBackground(new java.awt.Color(0, 102, 51));
        logInPanel.setBorder(new javax.swing.border.MatteBorder(null));

        LogInPageTitlePanel.setBackground(new java.awt.Color(102, 102, 102));

        LogInPageTitleLabel.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        LogInPageTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogInPageTitleLabel.setText("LOGIN");
        LogInPageTitleLabel.setToolTipText("");
        LogInPageTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout LogInPageTitlePanelLayout = new javax.swing.GroupLayout(LogInPageTitlePanel);
        LogInPageTitlePanel.setLayout(LogInPageTitlePanelLayout);
        LogInPageTitlePanelLayout.setHorizontalGroup(
            LogInPageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInPageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        LogInPageTitlePanelLayout.setVerticalGroup(
            LogInPageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInPageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        usernameTextField.setToolTipText("username");
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        passwordPasswordField.setToolTipText("password123");

        usernameLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setLabelFor(usernameTextField);
        usernameLabel.setText("Username:");

        passwordLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setLabelFor(passwordPasswordField);
        passwordLabel.setText("Password:");

        loginButton.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        loginButton.setText("Login!");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        SignUpButton.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        SignUpButton.setText("Sign Up!");
        SignUpButton.setToolTipText("");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogInPageTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(logInPanelLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameTextField)
                                    .addComponent(passwordPasswordField)
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SignUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(logInPanelLayout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogInPageTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        mainPanel.add(logInPanel, "card1");

        userProfilePanel.setBackground(new java.awt.Color(0, 102, 51));
        userProfilePanel.setBorder(new javax.swing.border.MatteBorder(null));

        UserProfilePageTitlePanel.setBackground(new java.awt.Color(102, 102, 102));

        UserProfilePageTitleLabel.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        UserProfilePageTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserProfilePageTitleLabel.setLabelFor(UserProfilePageTitlePanel);
        UserProfilePageTitleLabel.setText("User Profile");
        UserProfilePageTitleLabel.setToolTipText("");
        UserProfilePageTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout UserProfilePageTitlePanelLayout = new javax.swing.GroupLayout(UserProfilePageTitlePanel);
        UserProfilePageTitlePanel.setLayout(UserProfilePageTitlePanelLayout);
        UserProfilePageTitlePanelLayout.setHorizontalGroup(
            UserProfilePageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserProfilePageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UserProfilePageTitlePanelLayout.setVerticalGroup(
            UserProfilePageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserProfilePageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        DynamicUsernameLabel.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        DynamicUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        DynamicUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DynamicUsernameLabel.setText("@userName");
        DynamicUsernameLabel.setToolTipText("");

        UpdateProfileButton.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        UpdateProfileButton.setText("Update Profile");
        UpdateProfileButton.setToolTipText("");
        UpdateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProfileButtonActionPerformed(evt);
            }
        });

        DynamicPlayerSinceLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        DynamicPlayerSinceLabel.setForeground(new java.awt.Color(255, 255, 255));
        DynamicPlayerSinceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DynamicPlayerSinceLabel.setText("@createdDate");
        DynamicPlayerSinceLabel.setToolTipText("");
        DynamicPlayerSinceLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        playerSinceLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        playerSinceLabel.setForeground(new java.awt.Color(255, 255, 255));
        playerSinceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerSinceLabel.setLabelFor(DynamicPlayerSinceLabel);
        playerSinceLabel.setText("Player Since:");
        playerSinceLabel.setToolTipText("");
        playerSinceLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        gamesPlayedLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        gamesPlayedLabel.setForeground(new java.awt.Color(255, 255, 255));
        gamesPlayedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gamesPlayedLabel.setLabelFor(DynamicGamesPlayedLabel);
        gamesPlayedLabel.setText("Games Played:");
        gamesPlayedLabel.setToolTipText("");
        gamesPlayedLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        DynamicGamesPlayedLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        DynamicGamesPlayedLabel.setForeground(new java.awt.Color(255, 255, 255));
        DynamicGamesPlayedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DynamicGamesPlayedLabel.setText("@gamesPlayed");
        DynamicGamesPlayedLabel.setToolTipText("");
        DynamicGamesPlayedLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        totalWinsLabel.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        totalWinsLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalWinsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalWinsLabel.setText("Games Won!");
        totalWinsLabel.setToolTipText("");
        totalWinsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        DynamicTotalWinsLabel1.setFont(new java.awt.Font("Impact", 1, 45)); // NOI18N
        DynamicTotalWinsLabel1.setForeground(new java.awt.Color(255, 255, 255));
        DynamicTotalWinsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DynamicTotalWinsLabel1.setText("@totalWins");
        DynamicTotalWinsLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout userProfilePanelLayout = new javax.swing.GroupLayout(userProfilePanel);
        userProfilePanel.setLayout(userProfilePanelLayout);
        userProfilePanelLayout.setHorizontalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DynamicUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateProfileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserProfilePageTitlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addComponent(DynamicPlayerSinceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalWinsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(DynamicGamesPlayedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addComponent(playerSinceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DynamicTotalWinsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gamesPlayedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        userProfilePanelLayout.setVerticalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserProfilePageTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(DynamicUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playerSinceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gamesPlayedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DynamicTotalWinsLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DynamicPlayerSinceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DynamicGamesPlayedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalWinsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        mainPanel.add(userProfilePanel, "card3");

        leaderBoardPanel.setBackground(new java.awt.Color(0, 102, 51));
        leaderBoardPanel.setForeground(new java.awt.Color(255, 51, 51));

        LeaderBoardPageTitlePanel.setBackground(new java.awt.Color(102, 102, 102));

        LeaderBoardPageTitleLabel.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        LeaderBoardPageTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LeaderBoardPageTitleLabel.setLabelFor(LeaderBoardPageTitleLabel);
        LeaderBoardPageTitleLabel.setText("High Scores");
        LeaderBoardPageTitleLabel.setToolTipText("");
        LeaderBoardPageTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout LeaderBoardPageTitlePanelLayout = new javax.swing.GroupLayout(LeaderBoardPageTitlePanel);
        LeaderBoardPageTitlePanel.setLayout(LeaderBoardPageTitlePanelLayout);
        LeaderBoardPageTitlePanelLayout.setHorizontalGroup(
            LeaderBoardPageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeaderBoardPageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );
        LeaderBoardPageTitlePanelLayout.setVerticalGroup(
            LeaderBoardPageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeaderBoardPageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        leaderBoardScrollPane.setBackground(new java.awt.Color(0, 102, 51));
        leaderBoardScrollPane.setToolTipText("");

        LeaderBoardTable.setFont(new java.awt.Font("Impact", 0, 10)); // NOI18N
        LeaderBoardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User", "Games Won", "Games Played", "Player Since"
            }
        ));
        LeaderBoardTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        LeaderBoardTable.setRowHeight(30);
        LeaderBoardTable.setGridColor(new java.awt.Color(0, 102, 51));
        leaderBoardScrollPane.setViewportView(LeaderBoardTable);

        javax.swing.GroupLayout leaderBoardPanelLayout = new javax.swing.GroupLayout(leaderBoardPanel);
        leaderBoardPanel.setLayout(leaderBoardPanelLayout);
        leaderBoardPanelLayout.setHorizontalGroup(
            leaderBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leaderBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeaderBoardPageTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leaderBoardScrollPane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        leaderBoardPanelLayout.setVerticalGroup(
            leaderBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeaderBoardPageTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(leaderBoardScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        mainPanel.add(leaderBoardPanel, "card2");

        gamePlayPanel.setBackground(new java.awt.Color(0, 102, 51));

        GamePlayPageTitlePanel.setBackground(new java.awt.Color(102, 102, 102));

        GamePlayPageTitleLabel.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        GamePlayPageTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GamePlayPageTitleLabel.setLabelFor(GamePlayPageTitlePanel);
        GamePlayPageTitleLabel.setText("WAR");
        GamePlayPageTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout GamePlayPageTitlePanelLayout = new javax.swing.GroupLayout(GamePlayPageTitlePanel);
        GamePlayPageTitlePanel.setLayout(GamePlayPageTitlePanelLayout);
        GamePlayPageTitlePanelLayout.setHorizontalGroup(
            GamePlayPageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GamePlayPageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GamePlayPageTitlePanelLayout.setVerticalGroup(
            GamePlayPageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GamePlayPageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        computerDeckjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/card back.png"))); // NOI18N
        computerDeckjButton.setToolTipText("");

        playerDeckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/card back.png"))); // NOI18N
        playerDeckButton.setToolTipText("");
        playerDeckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerDeckButtonActionPerformed(evt);
            }
        });

        ComputerCardjLabel.setBackground(new java.awt.Color(255, 255, 255));
        ComputerCardjLabel.setForeground(new java.awt.Color(255, 255, 255));
        ComputerCardjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComputerCardjLabel.setToolTipText("");
        ComputerCardjLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ComputerCardjLabel.setPreferredSize(new java.awt.Dimension(149, 171));

        Player1CardjLabel.setBackground(new java.awt.Color(255, 255, 255));
        Player1CardjLabel.setForeground(new java.awt.Color(255, 255, 255));
        Player1CardjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1CardjLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Player1CardjLabel.setPreferredSize(new java.awt.Dimension(149, 171));

        DynamicPlayerCardsRemainingLabel.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        DynamicPlayerCardsRemainingLabel.setForeground(new java.awt.Color(255, 255, 255));
        DynamicPlayerCardsRemainingLabel.setLabelFor(playerDeckButton);
        DynamicPlayerCardsRemainingLabel.setText("@cardsRemaining");

        DynamicComputerCardsRemainingLabel.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        DynamicComputerCardsRemainingLabel.setForeground(new java.awt.Color(255, 255, 255));
        DynamicComputerCardsRemainingLabel.setLabelFor(computerDeckjButton);
        DynamicComputerCardsRemainingLabel.setText("@cardsRemaining");

        forfeitButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        forfeitButton.setText("Forfeit");
        forfeitButton.setToolTipText("");
        forfeitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forfeitButtonActionPerformed(evt);
            }
        });

        WinnerMessageLabel.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        WinnerMessageLabel.setForeground(new java.awt.Color(255, 255, 255));
        WinnerMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WinnerMessageLabel.setText("@winnerMessage");
        WinnerMessageLabel.setToolTipText("");

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePlayPanelLayout = new javax.swing.GroupLayout(gamePlayPanel);
        gamePlayPanel.setLayout(gamePlayPanelLayout);
        gamePlayPanelLayout.setHorizontalGroup(
            gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePlayPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePlayPanelLayout.createSequentialGroup()
                        .addComponent(playerDeckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gamePlayPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gamePlayPanelLayout.createSequentialGroup()
                                        .addComponent(forfeitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(gamePlayPanelLayout.createSequentialGroup()
                                        .addComponent(WinnerMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))))
                            .addGroup(gamePlayPanelLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(gamePlayPanelLayout.createSequentialGroup()
                        .addComponent(DynamicPlayerCardsRemainingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(computerDeckjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DynamicComputerCardsRemainingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(gamePlayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GamePlayPageTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePlayPanelLayout.createSequentialGroup()
                        .addComponent(Player1CardjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(ComputerCardjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        gamePlayPanelLayout.setVerticalGroup(
            gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePlayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GamePlayPageTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComputerCardjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(Player1CardjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePlayPanelLayout.createSequentialGroup()
                        .addGroup(gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerDeckButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(computerDeckjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gamePlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DynamicComputerCardsRemainingLabel)
                            .addComponent(DynamicPlayerCardsRemainingLabel)))
                    .addGroup(gamePlayPanelLayout.createSequentialGroup()
                        .addComponent(WinnerMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(forfeitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnlogout)))
                .addGap(22, 22, 22))
        );

        mainPanel.add(gamePlayPanel, "card3");

        signUpPanel.setBackground(new java.awt.Color(0, 102, 51));
        signUpPanel.setBorder(new javax.swing.border.MatteBorder(null));

        SignUpPageTitlePanel.setBackground(new java.awt.Color(102, 102, 102));

        SignupPageTitleLabel.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        SignupPageTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignupPageTitleLabel.setLabelFor(SignUpPageTitlePanel);
        SignupPageTitleLabel.setText("Sign Up");
        SignupPageTitleLabel.setToolTipText("");
        SignupPageTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout SignUpPageTitlePanelLayout = new javax.swing.GroupLayout(SignUpPageTitlePanel);
        SignUpPageTitlePanel.setLayout(SignUpPageTitlePanelLayout);
        SignUpPageTitlePanelLayout.setHorizontalGroup(
            SignUpPageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupPageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SignUpPageTitlePanelLayout.setVerticalGroup(
            SignUpPageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupPageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        UsernameTextField.setToolTipText("PlayerJohn");

        NameTextField.setToolTipText("John Doe");

        EmailTextField.setToolTipText("john.doe@email.com");

        matchPasswordField.setToolTipText("password123");

        newPasswordField.setToolTipText("password123");

        emailLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setLabelFor(EmailTextField);
        emailLabel.setText("Email:");
        emailLabel.setToolTipText("");

        nameLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setLabelFor(NameTextField);
        nameLabel.setText("Name:");

        newUsernameLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        newUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        newUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newUsernameLabel.setLabelFor(UsernameTextField);
        newUsernameLabel.setText("Username:");

        matchPasswordLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        matchPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        matchPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        matchPasswordLabel.setLabelFor(matchPasswordField);
        matchPasswordLabel.setText("Confirm Password:");
        matchPasswordLabel.setToolTipText("");

        newPasswordLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        newPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        newPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newPasswordLabel.setLabelFor(newPasswordField);
        newPasswordLabel.setText("Password:");
        newPasswordLabel.setToolTipText("");

        submitButton.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignUpPageTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                                .addComponent(newUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(signUpPanelLayout.createSequentialGroup()
                                    .addComponent(matchPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(matchPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpPageTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matchPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        mainPanel.add(signUpPanel, "card3");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));

        leaderBoardButton.setFont(new java.awt.Font("Impact", 0, 10)); // NOI18N
        leaderBoardButton.setText("High Scores");
        leaderBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBoardButtonActionPerformed(evt);
            }
        });

        userProfileButton.setFont(new java.awt.Font("Impact", 0, 10)); // NOI18N
        userProfileButton.setText("User Profile");
        userProfileButton.setMaximumSize(new java.awt.Dimension(61, 19));
        userProfileButton.setMinimumSize(new java.awt.Dimension(61, 19));
        userProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProfileButtonActionPerformed(evt);
            }
        });

        gameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/card game Logo.jpg"))); // NOI18N
        gameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(leaderBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(gameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(userProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameButton)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leaderBoardButton)
                    .addComponent(userProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leaderBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBoardButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(leaderBoardPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_leaderBoardButtonActionPerformed

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(gamePlayPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

        wargame = new WarGameConnector();
        wargame.startNewGame();
        WinnerMessageLabel.setText(wargame.winnerMessage());
        DynamicPlayerCardsRemainingLabel.setText(wargame.player1Score());
        DynamicComputerCardsRemainingLabel.setText(wargame.player2Score());
    }//GEN-LAST:event_gameButtonActionPerformed

    private void userProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProfileButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(userProfilePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        DynamicGamesPlayedLabel.setText(userdata.GamesPlayed());
        //DynamicPlayerSinceLabel.setText(userdata.);
        DynamicTotalWinsLabel1.setText(userdata.GamesWon());
        DynamicUsernameLabel.setText(Username);
    }//GEN-LAST:event_userProfileButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(signUpPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(logInPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

        userdata.createFolder();
        userdata.readFile();
        userdata.checkLines();
        userdata.addData();

        /*changed aftere video  -->.*/
        JOptionPane.showMessageDialog(null, "Accout Created");

        Username = UsernameTextField.getText();
        Password = newPasswordField.getText();
        Password = matchPasswordField.getText();
        Email = EmailTextField.getText();
        Name = NameTextField.getText();

    }//GEN-LAST:event_submitButtonActionPerformed

    private void UpdateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProfileButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(signUpPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_UpdateProfileButtonActionPerformed

    private void playerDeckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerDeckButtonActionPerformed
        //newGameRound
        wargame.newRound();
        try {
            //DisplayCardImages
            Player1CardjLabel.setIcon(wargame.player1Image());
            ComputerCardjLabel.setIcon(wargame.player2Image());
        } catch (IOException ex) {
            Logger.getLogger(CardGameAppUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        //UpdateScores
        DynamicPlayerCardsRemainingLabel.setText(wargame.player1Score());
        DynamicComputerCardsRemainingLabel.setText(wargame.player2Score());
        //setRoundWinner
        //CheckGameWinner        
        WinnerMessageLabel.setText(wargame.winnerMessage());
    }//GEN-LAST:event_playerDeckButtonActionPerformed

    private void forfeitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forfeitButtonActionPerformed
        wargame.startNewGame();
        WinnerMessageLabel.setText(wargame.winnerMessage());
        DynamicPlayerCardsRemainingLabel.setText(wargame.player1Score());
        DynamicComputerCardsRemainingLabel.setText(wargame.player2Score());
    }//GEN-LAST:event_forfeitButtonActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(gamePlayPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

        wargame = new WarGameConnector();
        wargame.startNewGame();
        WinnerMessageLabel.setText(wargame.winnerMessage());
        DynamicPlayerCardsRemainingLabel.setText(wargame.player1Score());
        DynamicComputerCardsRemainingLabel.setText(wargame.player2Score());

        userdata.createFolder();
        userdata.readFile();
        userdata.checkLines();
        userdata.validateUserDataLogic(Username, Password);


    }//GEN-LAST:event_loginButtonActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(logInPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardGameAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardGameAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardGameAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardGameAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardGameAppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ComputerCardjLabel;
    private javax.swing.JLabel DynamicComputerCardsRemainingLabel;
    private javax.swing.JLabel DynamicGamesPlayedLabel;
    private javax.swing.JLabel DynamicPlayerCardsRemainingLabel;
    private javax.swing.JLabel DynamicPlayerSinceLabel;
    private javax.swing.JLabel DynamicTotalWinsLabel1;
    private javax.swing.JLabel DynamicUsernameLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel GamePlayPageTitleLabel;
    private java.awt.Panel GamePlayPageTitlePanel;
    private javax.swing.JLabel LeaderBoardPageTitleLabel;
    private java.awt.Panel LeaderBoardPageTitlePanel;
    private javax.swing.JTable LeaderBoardTable;
    private javax.swing.JLabel LogInPageTitleLabel;
    private java.awt.Panel LogInPageTitlePanel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel Player1CardjLabel;
    private javax.swing.JButton SignUpButton;
    private java.awt.Panel SignUpPageTitlePanel;
    private javax.swing.JLabel SignupPageTitleLabel;
    private javax.swing.JButton UpdateProfileButton;
    private javax.swing.JLabel UserProfilePageTitleLabel;
    private java.awt.Panel UserProfilePageTitlePanel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel WinnerMessageLabel;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton computerDeckjButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton forfeitButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JPanel gamePlayPanel;
    private javax.swing.JLabel gamesPlayedLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton leaderBoardButton;
    private javax.swing.JPanel leaderBoardPanel;
    private javax.swing.JScrollPane leaderBoardScrollPane;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField matchPasswordField;
    private javax.swing.JLabel matchPasswordLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel newUsernameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JButton playerDeckButton;
    private javax.swing.JLabel playerSinceLabel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel totalWinsLabel;
    private javax.swing.JButton userProfileButton;
    private javax.swing.JPanel userProfilePanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
